name: Update trending topics

on:
  schedule:
    # Runs once every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual trigger via GitHub UI
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  update-trending:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytrends
      - name: Run trending update script
        run: |
          python trending.py
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add trending.json
            git commit -m "Update trending topics"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
